import numpy as np
a=np.arange(9,dtype=np.float_).reshape(3,3)
print("First:")
print(a)
print('\n')
b=np.array([10,10,10])
print("Second:")
print(b)
print('\n')
print("Add arrays")
print(np.add(a,b))
print('\n')
print("Subtract arrays")
print(np.subtract(a,b))
print('\n')
print("Multiply arrays")
print(np.multiply(a,b))
print('\n')
print("divide arrays")
print(np.divide(a,b))